// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOJD77JEMVhKnzuuOZABmsiY7z4ehGKY',
    appId: '1:692389950974:web:430073135ea3f7b561bcaf',
    messagingSenderId: '692389950974',
    projectId: 'my-project-b4f36',
    authDomain: 'my-project-b4f36.firebaseapp.com',
    storageBucket: 'my-project-b4f36.firebasestorage.app',
    measurementId: 'G-BGPCG9SFZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iANyA7i6QIP3AQsrLivNuZ9MgNPAvtk',
    appId: '1:692389950974:android:8141c46c63d9d61961bcaf',
    messagingSenderId: '692389950974',
    projectId: 'my-project-b4f36',
    storageBucket: 'my-project-b4f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByh55lQ-yt6gtS0KWKNpfvvTcqDSPfFYU',
    appId: '1:692389950974:ios:bad8bce31bc6b8c261bcaf',
    messagingSenderId: '692389950974',
    projectId: 'my-project-b4f36',
    storageBucket: 'my-project-b4f36.firebasestorage.app',
    iosBundleId: 'com.example.chatConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByh55lQ-yt6gtS0KWKNpfvvTcqDSPfFYU',
    appId: '1:692389950974:ios:bad8bce31bc6b8c261bcaf',
    messagingSenderId: '692389950974',
    projectId: 'my-project-b4f36',
    storageBucket: 'my-project-b4f36.firebasestorage.app',
    iosBundleId: 'com.example.chatConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEOJD77JEMVhKnzuuOZABmsiY7z4ehGKY',
    appId: '1:692389950974:web:b6ac5af23a56cf7161bcaf',
    messagingSenderId: '692389950974',
    projectId: 'my-project-b4f36',
    authDomain: 'my-project-b4f36.firebaseapp.com',
    storageBucket: 'my-project-b4f36.firebasestorage.app',
    measurementId: 'G-M4QVE1RDS1',
  );
}
